#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

var answers = [
  "YES",
  "No",
  "Hope not",
   "Hope so",
   "Maybe",
  "definitely",
  "Absolutly Not",
  "The answer lies within you",
  c.red + "Question denied." + c.x + "Try again later",
  "Yup"
]
  var easterEgg1 = ["Count to 10", "1,2,3,4,5,6,7,8,9,10"];
  var easterEgg2 = ["What is amazing", "YOU!"];
  var easterEggs = [easterEgg1, easterEgg2];

function print(message) {
  process.stdout.write(message + "\n");
}
print(c.clear + c.multi("Welcome to the Magic Eightball"));

